# Generated by Django 4.2.4 on 2023-09-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_resource_course_star_course_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
