# Generated by Django 4.2.4 on 2023-09-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_nikname_user_profile'),
        ('courses', '0006_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Star',
            field=models.ManyToManyField(blank=True, related_name='Star', to='user.user'),
        ),
        migrations.AlterField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Likes', to='user.user'),
        ),
    ]
