# Generated by Django 4.2.4 on 2023-09-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_bought'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chapters',
            new_name='Chapter',
        ),
    ]
