# Generated by Django 4.2.4 on 2023-09-22 10:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_chapters_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=django.core.files.storage.FileSystemStorage(base_url='/Videos', location='/amirooo.net/Backend/amirooo/media')),
        ),
    ]
