# Generated by Django 4.2.4 on 2023-09-23 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_video_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_title',
            new_name='title',
        ),
    ]
