# Generated by Django 4.2.4 on 2023-09-23 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_chapter_chapter_videos_remove_video_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
