# Generated by Django 4.2.4 on 2023-09-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='videos_lenth',
            field=models.IntegerField(default=0),
        ),
    ]
