# Generated by Django 4.2.4 on 2024-01-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
