# Generated by Django 4.2.4 on 2023-09-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_username_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Fname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Lname',
        ),
        migrations.AddField(
            model_name='user',
            name='Fullname',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
