# Generated by Django 4.2.4 on 2023-09-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_fname_remove_user_lname_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Nikname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='Profile',
            field=models.ImageField(default='defultProfile.jpg', upload_to='profiles'),
        ),
    ]
