# Generated by Django 4.2.4 on 2023-09-21 20:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_nikname_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Bio',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
