# Generated by Django 4.2.4 on 2023-09-24 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='User',
            new_name='user',
        ),
    ]
