# Generated by Django 4.2.4 on 2023-10-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_course_star_alter_course_likes_and_more'),
        ('user', '0007_rename_user_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_course',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
