# Generated by Django 4.2.4 on 2023-11-27 16:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', tinymce.models.HTMLField(blank=True)),
                ('previev', models.ImageField(upload_to='updates/')),
                ('learn_by', models.BooleanField(default=False)),
            ],
        ),
    ]
