# Generated by Django 4.2.4 on 2023-11-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_updates_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updates',
            old_name='learn_by',
            new_name='read',
        ),
        migrations.AddField(
            model_name='updates',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
