# Generated by Django 4.2.4 on 2023-11-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_updates_link_remove_updates_previev'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='previev',
            field=models.ImageField(blank=True, upload_to='updates/'),
        ),
    ]
